import type { SystemDesignContent } from '../../_shared/types';

export const content: SystemDesignContent = {
  title: 'CDN (Content Delivery Network)',
  sections: [
    {
      id: 'section-0',
      title: '基本概念',
      blocks: [
        { type: 'paragraph', text: '現代系統通常面向全球使用者提供服務,這使得將內容快速傳送給世界各地的使用者 變得具有挑戰性。使用者(以及面試官)期望快速的載入時間,而延遲可能導致不良 的使用者體驗與流量流失。內容傳遞網路(Content Delivery Network,CDN)是一種 使用分散式伺服器,根據使用者地理位置來傳送內容的快取系統。CDN 通常用於傳送 靜態內容,例如圖片、影片與 HTML 檔案,但也可以用於傳送動態內容,例如 API 回 應。' },
        { type: 'paragraph', text: 'CDN 的運作方式是將內容快取在靠近使用者的伺服器上。當使用者請求內容時,CDN 會將請求導向距離最近的伺服器。如果該伺服器已經快取了該內容,CDN 會直接回傳 快取內容。如果該伺服器沒有快取該內容,CDN 會從原始伺服器(origin server)抓 取內容,將其快取在該伺服器上,然後再回傳給使用者。' },
        { type: 'paragraph', text: '在面試中,CDN 最常見的應用場景是快取靜態媒體資產,例如圖片與影片。舉例來 說,如果你有一個像 Instagram 這樣的社群平台,你可能會使用 CDN 來快取使用者的 頭像圖片。這樣可以讓世界各地的使用者都能快速載入頭像圖片。' },
      ],
    },
    {
      id: 'section-1',
      title: '架構特徵',
      blocks: [
        { type: 'paragraph', text: 'Edge Node (邊緣節點)' },
        { type: 'paragraph', text: '最靠近使用者的伺服器,負責回應快取內容。' },
        { type: 'paragraph', text: 'Origin Server (源站)' },
        { type: 'paragraph', text: '原始資料存放位置(例如應用伺服器或 Blob Storage)。' },
        { type: 'paragraph', text: 'Cache Hierarchy' },
        { type: 'paragraph', text: '多層快取設計:Edge Cache → Regional Cache → Origin。' },
        { type: 'paragraph', text: '協定支援' },
        { type: 'paragraph', text: 'HTTP/HTTPS,部分 CDN 支援 WebSocket 與 API 加速。' },
        { type: 'paragraph', text: '全球分佈' },
        { type: 'paragraph', text: '多個 PoP (Point of Presence),減少跨國延遲。' },
      ],
    },
    {
      id: 'section-2',
      title: '常見功能',
      blocks: [
        { type: 'paragraph', text: '內容快取 (Caching)' },
        { type: 'paragraph', text: '對靜態檔案(CSS、JS、圖片、影片)進行快取。' },
        { type: 'paragraph', text: '動態加速 (Dynamic Content Acceleration)' },
        { type: 'paragraph', text: 'TCP 優化、路由優化,縮短跨國傳輸延遲。' },
        { type: 'paragraph', text: '安全 (Security)' },
        { type: 'paragraph', text: 'DDoS 防護、WAF (Web Application Firewall)、Bot 防護。' },
        { type: 'paragraph', text: '流量壓縮與優化' },
        { type: 'paragraph', text: 'Gzip / Brotli 壓縮、圖片壓縮、自動轉 WebP。' },
        { type: 'paragraph', text: 'Edge Compute (邊緣運算)' },
        { type: 'paragraph', text: '部分 CDN(Cloudflare Workers、Akamai EdgeWorkers)支援在邊緣節點上 執行程式邏輯。' },
      ],
    },
    {
      id: 'section-3',
      title: '常見產品與服務',
      blocks: [
        { type: 'paragraph', text: '商業 CDN' },
        { type: 'paragraph', text: 'Cloudflare' },
        { type: 'paragraph', text: 'Akamai' },
        { type: 'paragraph', text: 'Fastly' },
        { type: 'paragraph', text: '雲端服務商提供的 CDN' },
        { type: 'paragraph', text: 'AWS CloudFront' },
        { type: 'paragraph', text: 'Azure CDN' },
        { type: 'paragraph', text: 'Google Cloud CDN' },
      ],
    },
    {
      id: 'section-4',
      title: '適用場景',
      blocks: [
        { type: 'paragraph', text: '靜態資源分發' },
        { type: 'paragraph', text: '圖片、影片、JS/CSS、HTML' },
        { type: 'paragraph', text: 'API 加速' },
        { type: 'paragraph', text: '提高 API 回應速度,減少跨區延遲' },
        { type: 'paragraph', text: '大型活動流量高峰' },
        { type: 'paragraph', text: '遊戲發佈、線上演唱會、直播' },
        { type: 'paragraph', text: '安全防護' },
        { type: 'paragraph', text: '防止惡意流量直接打到源站' },
      ],
    },
    {
      id: 'cache-invalidation-strategy-in-cdn',
      title: 'Cache Invalidation Strategy in CDN',
      blocks: [
        { type: 'paragraph', text: 'TTL (Time-to-Live)' },
        { type: 'paragraph', text: '靜態檔案設 TTL,例如圖片設一週,CSS 設一天' },
        { type: 'paragraph', text: '版本號 / Hash Busting' },
        { type: 'paragraph', text: '在 URL 加上版本號或 hash,例如:app.css?v=12345' },
        { type: 'paragraph', text: 'Purge API' },
        { type: 'paragraph', text: '主動通知 CDN 清除指定檔案快取' },
        { type: 'paragraph', text: 'Stale-while-revalidate' },
        { type: 'paragraph', text: '提供過期但仍可用的快取,同時在背景更新' },
      ],
    },
    {
      id: 'cdn',
      title: '在系統設計面試中如何談 CDN',
      blocks: [
        { type: 'paragraph', text: '不要在所有流量前都畫 CDN → 只針對靜態資源與高頻內容。' },
        { type: 'paragraph', text: '正確表達方式:' },
        { type: 'paragraph', text: '系統對靜態檔案(圖片、影片、CSS/JS)使用 CDN,減少延遲與源站壓力。' },
        { type: 'paragraph', text: 'API 若有全球用戶,也可透過 CDN 進行加速。' },
        { type: 'paragraph', text: '若需要保護源站(origin),CDN 也可作為安全防護層(DDoS/WAF)。' },
        { type: 'paragraph', text: '常見面試追問' },
        { type: 'paragraph', text: '如何確保快取更新? → TTL + Hash Busting' },
        { type: 'paragraph', text: '動態內容怎麼處理? → Edge Compute / API 加速' },
        { type: 'paragraph', text: 'CDN 掛掉怎麼辦? → 設定 fallback 到 Origin' },
      ],
    },
  ],
};
