import type { SystemDesignContent } from '../../_shared/types';

export const content: SystemDesignContent = {
  title: 'CAP Theorem',
  sections: [
    {
      id: 'cap-theorem',
      title: 'CAP Theorem',
      blocks: [
        { type: 'paragraph', text: 'CAP 定理(Consistency, Availability, Partition Tolerance)是分散式系統中的一個基 本理論。它指出在一個分散式系統中,當節點間無法通訊的狀況發生時,不可能同時 完全滿足以下三個特性:' },
        { type: 'list', ordered: true, items: ['一致性(Consistency):所有節點在同一時間看到的資料是一致的。', '可用性(Availability):每個請求都能在有限時間內獲得回應,不會長時間等'] },
        { type: 'paragraph', text: '待。' },
        { type: 'list', ordered: true, items: ['分區容錯性(Partition Tolerance):系統能在網路分區或訊息丟失的情況下繼'] },
        { type: 'paragraph', text: '續運作。' },
        { type: 'paragraph', text: '當網路分區發生時,我們需要決定是優先考慮可用性還是一致性?' },
        { type: 'paragraph', text: '根據 CAP 定理,一個系統最多只能同時滿足其中的兩個特性。例如:' },
        { type: 'paragraph', text: 'CP 系統:保證一致性與分區容錯,但在網路分區時可能犧牲可用性。' },
        { type: 'paragraph', text: 'AP 系統:保證可用性與分區容錯,但可能犧牲一致性。' },
        { type: 'paragraph', text: 'CA 系統:保證一致性與可用性,但在真實世界中幾乎不可能實現,因為網路分區 不可避免。' },
        { type: 'subheading', text: 'Consistency vs. Availability' },
        { type: 'paragraph', text: '選擇 Consistency 意味著系統中的所有節點在同一時間都會看到相同的資料。當一次 寫入發生後,所有後續的讀取都會返回這個值,不論請求打到哪個節點。然而,在發 生網路分區時,部分節點可能會變得不可用,以維持這種一致性的保證。' },
        { type: 'paragraph', text: '選擇 Availability 則代表每個請求都會收到回應,即使在網路分區期間也是如此。代價 是不同的節點可能會暫時擁有不同版本的資料,導致資料不一致。系統最終會調和這 些差異,但無法保證何時完成。' },
        { type: 'paragraph', text: '在系統設計面試中,可用性通常應該是預設選擇。只有在那些無法容忍過期資料的系 統中,才需要強一致性。' },
        { type: 'subheading', text: '強一致性系統的範例' },
        { type: 'paragraph', text: '有些系統對一致性要求極高,因為即使是短暫的不一致也會造成嚴重後果,例如:' },
        { type: 'paragraph', text: '庫存管理系統:需要精確追蹤庫存量,以避免商品超賣導致顧客抱怨、退款。' },
        { type: 'paragraph', text: '有限資源的預訂系統(航空座位、活動門票、飯店房間):必須避免重複預訂。' },
        { type: 'paragraph', text: '銀行系統:帳戶餘額必須在所有節點間保持一致,以防止詐騙。' },
        { type: 'paragraph', text: '這些系統的關鍵特徵是:任何不一致,即使是暫時的,也可能導致重大的商業或技術 問題。' },
        { type: 'subheading', text: '真實世界案例:ATM 提款機系統' },
        { type: 'paragraph', text: '想像銀行有多個分行與提款機(分散式系統),帳戶餘額資料需要共享。' },
        { type: 'list', ordered: true, items: ['Consistency(一致性)'] },
        { type: 'paragraph', text: '你在台北提款 1000 元,系統立刻更新,台中的 ATM 查到的餘額馬上減少。' },
        { type: 'paragraph', text: '保證大家看到的數據都是最新、相同的。' },
        { type: 'paragraph', text: '但是如果台北和台中網路斷線,台中就不能讓你提款,因為無法確定最新餘 額。' },
        { type: 'paragraph', text: '➡️ C + P,放棄 A:犧牲可用性,但保證一致。' },
        { type: 'list', ordered: true, items: ['Availability(可用性)'] },
        { type: 'paragraph', text: '假設你在台北提款 1000 元,但台中 ATM 因網路斷線暫時無法同步資料,系 統仍允許你提款。' },
        { type: 'paragraph', text: '使用者體驗好(永遠能提款),但可能造成超支(兩邊各領 1000)。' },
        { type: 'paragraph', text: '➡️ A + P,放棄 C:犧牲一致性,但保證可用。' },
        { type: 'list', ordered: true, items: ['Partition Tolerance(分區容忍性)'] },
        { type: 'paragraph', text: '網路不可能永遠不斷,所以分散式系統必須能忍受分區,也就是承受網路暫時 斷開。' },
        { type: 'paragraph', text: '因此 P 幾乎一定要保留,只能在 C 和 A 之間取捨。' },
      ],
    },
  ],
  selfTest: [
    { question: '為什麼 CA 系統在真實的分散式系統中幾乎不存在?', answer: '因為在分散式系統中,網路分區(Partition)是不可避免的,所以 P 幾乎是必選 的。當 P 必須保留時,只能在 C 和 A 之間二選一,CA 系統等於假設網路永遠不會 出問題,這不切實際。' },
    { question: '以下哪些場景最適合選擇 CP(強一致性)?(A) 社群媒體動態牆 (B) 飯店訂房系 統 (C) 使用者頭像快取 (D) 銀行帳戶餘額', answer: '答案:(B) 和 (D) 飯店訂房系統不能超賣(同一房間賣給兩人),銀行帳戶餘額必須精確。這些場景 中,即使短暫的不一致也會造成嚴重後果。社群動態牆和頭像快取可以容忍短暫的 資料不一致。' },
    { question: '在 ATM 案例中,如果系統選擇 AP,台北和台中同時提款可能造成什麼問題?', answer: '可能造成超支(overdraft)。兩邊的 ATM 因為網路斷線無法同步餘額,各自允許 提款,結果使用者實際提取的總金額超過帳戶餘額。' },
    { question: '在系統設計面試中,預設應該選擇一致性還是可用性?', answer: '可用性(Availability)通常是預設選擇。只有在那些無法容忍過期資料的系統(如 庫存管理、預訂系統、銀行系統)中,才需要選擇強一致性。' },
  ],
};
