import type { SystemDesignContent } from '../../_shared/types';

export const content: SystemDesignContent = {
  title: 'Load Balancer',
  sections: [
    {
      id: 'section-0',
      title: '基本概念',
      blocks: [
        { type: 'paragraph', text: 'Load Balancer (負載平衡器) 是一種在 多個伺服器或服務實例之間分配流量 的元 件。' },
        { type: 'paragraph', text: '核心目的:避免單一伺服器過載,提升系統可用性與擴展性。' },
        { type: 'paragraph', text: '對客戶端來說,它只看到一個入口,實際上流量可能被分配到多台後端伺服器。' },
      ],
    },
    {
      id: 'section-1',
      title: '核心功能',
      blocks: [
        { type: 'paragraph', text: '流量分配(Traffic Distribution)' },
        { type: 'paragraph', text: 'Load Balancer 最直覺的角色就是「把流量分出去」,但真正重要的是它怎麼分,以及 分流是否能跟著流量變化而調整。' },
        { type: 'paragraph', text: '在小規模系統中,流量分配可能只是單純的 Round Robin,把請求平均送到多台機 器。但當流量變大、請求變複雜時,分流策略就會變成系統穩定性的關鍵。例如:' },
        { type: 'paragraph', text: 'API 請求長短差異大' },
        { type: 'paragraph', text: '有部分節點規格較好' },
        { type: 'paragraph', text: '某些機器正處於 GC 或 CPU 高峰' },
        { type: 'paragraph', text: '這時如果分配策略太天真,就會出現表面平均、實際不平均的問題。成熟的 Load Balancer 通常會結合即時負載資訊(連線數、延遲、錯誤率)做動態調整。' },
        { type: 'paragraph', text: '流量分配的本質不是「平均」,而是「讓整體系統吞吐量最大化,同時避免局部過 載」。' },
        { type: 'paragraph', text: '健康檢查(Health Check)' },
        { type: 'paragraph', text: '健康檢查是 Load Balancer 真正讓系統具備自動容錯能力的核心。' },
        { type: 'paragraph', text: '它會定期對後端節點發送請求,例如:' },
        { type: 'paragraph', text: 'HTTP /health  endpoint' },
        { type: 'paragraph', text: 'TCP port 檢查' },
        { type: 'paragraph', text: '或自定義的應用層檢測' },
        { type: 'paragraph', text: '如果連續多次檢查失敗,該節點就會被暫時移出流量池。當節點恢復正常後,再重新 加入。' },
        { type: 'paragraph', text: '這裡的設計重點在於:' },
        { type: 'paragraph', text: '檢查頻率太低,故障切換慢' },
        { type: 'paragraph', text: '檢查頻率太高,可能造成額外負擔' },
        { type: 'paragraph', text: '檢查邏輯過於簡單,可能誤判(例如服務還活著但依賴的 DB 已掛)' },
        { type: 'paragraph', text: '健康檢查實際上是自動化運維的一部分,它讓「壞節點」在沒有人工介入的情況下被 隔離。' },
        { type: 'paragraph', text: '高可用性(High Availability)' },
        { type: 'paragraph', text: 'Load Balancer 本身也是關鍵基礎設施。如果它掛掉,整個系統就會變成單點故障。' },
        { type: 'paragraph', text: '因此在實務上,Load Balancer 通常會:' },
        { type: 'paragraph', text: '至少部署兩台' },
        { type: 'paragraph', text: '使用 failover 機制' },
        { type: 'paragraph', text: '搭配 VIP(Virtual IP)或雲端托管 LB 服務' },
        { type: 'paragraph', text: '在雲環境中,像託管式 Load Balancer 服務(例如雲端 L4/L7 LB)通常已內建高可用 設計。但在自建架構中,必須考慮:' },
        { type: 'paragraph', text: 'LB 節點間的同步' },
        { type: 'paragraph', text: 'DNS failover' },
        { type: 'paragraph', text: '或使用 anycast' },
        { type: 'paragraph', text: '高可用性的本質不是「有備份」,而是故障發生時流量能否在可接受時間內自動轉 移。' },
        { type: 'paragraph', text: 'SSL 終結(SSL Termination)' },
        { type: 'paragraph', text: '在 HTTPS 流量中,TLS 握手與加解密會消耗 CPU。如果每台後端伺服器都處理 TLS,整體成本會放大。' },
        { type: 'paragraph', text: 'SSL Termination 的做法是:' },
        { type: 'list', ordered: true, items: ['在 Load Balancer 層完成 TLS 握手與解密', '後端只處理純 HTTP 流量'] },
        { type: 'paragraph', text: '這樣的好處包括:' },
        { type: 'paragraph', text: '減少後端 CPU 負擔' },
        { type: 'paragraph', text: '憑證集中管理' },
        { type: 'paragraph', text: '更容易統一更新 TLS 設定' },
        { type: 'paragraph', text: '不過也有設計上的考量,例如內網是否需要再次加密(mTLS)、是否有合規要求不能 明文傳輸等。' },
        { type: 'paragraph', text: '在高流量系統中,SSL Termination 幾乎是標準配置。' },
        { type: 'paragraph', text: 'Session Persistence(Sticky Session)' },
        { type: 'paragraph', text: '在某些系統中,使用者狀態保存在應用伺服器記憶體裡,例如購物車或臨時 session。' },
        { type: 'paragraph', text: '如果每次請求都被導向不同後端,就會導致 session 丟失。因此 Load Balancer 可以 透過 cookie 或 IP hash,讓同一使用者的請求持續導向同一台機器。' },
        { type: 'paragraph', text: '這種做法可以快速解決狀態同步問題,但會帶來兩個風險:' },
        { type: 'paragraph', text: '流量分佈不均' },
        { type: 'paragraph', text: '當節點掛掉時,session 直接消失' },
        { type: 'paragraph', text: '在可擴展架構中,更理想的做法通常是把 session 外移到 Redis 或資料庫,讓應用層 保持 stateless,減少對 Sticky Session 的依賴。' },
        { type: 'paragraph', text: 'Sticky Session 比較像是過渡方案,而不是長期最優架構。' },
        { type: 'paragraph', text: '多區域分流(Global Load Balancing)' },
        { type: 'paragraph', text: '當系統跨多個資料中心或地理區域部署時,Load Balancer 的角色會提升到全球層級。' },
        { type: 'paragraph', text: '這時候分流依據可能包括:' },
        { type: 'paragraph', text: '使用者地理位置' },
        { type: 'paragraph', text: 'DNS latency' },
        { type: 'paragraph', text: '即時回應時間' },
        { type: 'paragraph', text: '區域健康狀況' },
        { type: 'paragraph', text: '常見做法包括 DNS-based routing 或 Anycast IP。' },
        { type: 'paragraph', text: '全球分流的核心目標有兩個:' },
        { type: 'list', ordered: true, items: ['降低使用者延遲', '當某個區域故障時,自動切換到其他區域'] },
        { type: 'paragraph', text: '這層設計通常與災難復原(Disaster Recovery)策略緊密相關。' },
      ],
    },
    {
      id: 'section-2',
      title: '常見演算法 (Load Balancing Algorithms)',
      blocks: [
        { type: 'list', ordered: true, items: ['Round Robin'] },
        { type: 'paragraph', text: 'Round Robin 是最直覺、最公平的分配方式。每個新請求依序丟給下一台伺服器,不 考慮當前負載狀況。它假設每個請求的成本大致相同、每台機器性能接近。' },
        { type: 'paragraph', text: '在 CPU-bound 且請求處理時間差不多的場景下,這種方法簡單有效。但如果請求時間 差異很大,例如有些 API 只需 5ms,有些卻要 2 秒,Round Robin 可能會讓某些節點 積壓長請求而變慢,形成實際負載不均。' },
        { type: 'paragraph', text: '它的優點是實作簡單、開銷低,適合大多數 stateless web 服務作為預設選擇。' },
        { type: 'list', ordered: true, items: ['Least Connections'] },
        { type: 'paragraph', text: 'Least Connections 會把新請求送到目前「活躍連線數最少」的伺服器。它的核心假設 是:連線數可以近似代表負載。' },
        { type: 'paragraph', text: '這在長連線場景(例如 WebSocket、資料庫 proxy、API 可能會 hold connection)特 別有效。當不同請求處理時間差異大時,Least Connections 比 Round Robin 更能動 態調整流量。' },
        { type: 'paragraph', text: '不過它也有盲點:連線數少不一定代表 CPU 使用率低。如果某台機器在做重計算但連 線數不多,它仍然可能被分配更多請求。因此它比 Round Robin 聰明,但仍然不是完 美的負載衡量方式。' },
        { type: 'list', ordered: true, items: ['IP Hash'] },
        { type: 'paragraph', text: 'IP Hash 會對客戶端 IP 做 hash,讓同一個使用者的請求穩定導向同一台伺服器。這種 策略常見於需要 session stickiness 的場景,例如伺服器記憶體中保存使用者狀態,而 沒有使用外部 session store。' },
        { type: 'paragraph', text: '它的好處是簡單地實現「黏性會話」,減少跨機器同步成本。但代價是分佈可能不 均。如果某些 IP(例如企業 NAT 出口)流量特別大,就會集中壓在某一台機器上。此 外,當節點數量改變時,hash 結果通常會大幅變動,造成 session 重新分配。' },
        { type: 'paragraph', text: '在現代架構中,若能把 session 外移到 Redis 或 database,通常會避免依賴 IP Hash。' },
        { type: 'list', ordered: true, items: ['Weighted Round Robin'] },
        { type: 'paragraph', text: 'Weighted Round Robin 是 Round Robin 的延伸版本,允許根據伺服器性能給不同權 重。性能好的機器會被分配更多請求。' },
        { type: 'paragraph', text: '這在混合規格部署(例如部分新機器、部分舊機器,或不同 CPU 核心數)時特別有 用。它仍然維持 Round Robin 的簡單性,但能反映硬體差異。' },
        { type: 'paragraph', text: '需要注意的是它使用的是靜態權重,如果實際負載狀況會快速變動,僅靠權重未必能 精準反映即時壓力。' },
        { type: 'paragraph', text: '問題反思:試著從工程師的角度思考,如果有多個 Load Balancer 同時運作,你會怎 麼設計分流演算法,讓它們不需要共享狀態就能各自做出路由決策?' },
      ],
    },
    {
      id: 'section-3',
      title: '常見產品與服務',
      blocks: [
        { type: 'paragraph', text: '硬體型:F5, Citrix NetScaler' },
        { type: 'paragraph', text: '軟體型:NGINX, HAProxy, Envoy' },
        { type: 'paragraph', text: '雲端服務:' },
        { type: 'paragraph', text: 'AWS Elastic Load Balancing (ALB, NLB)' },
        { type: 'paragraph', text: 'GCP Load Balancer' },
        { type: 'paragraph', text: 'Azure Load Balancer' },
      ],
    },
    {
      id: 'section-4',
      title: '適用場景',
      blocks: [
        { type: 'paragraph', text: 'Web / API 服務:流量導向多台應用伺服器' },
        { type: 'paragraph', text: '微服務架構:服務之間流量分配' },
        { type: 'paragraph', text: '多地部署:跨區域分流,讓用戶請求到最近的資料中心' },
        { type: 'paragraph', text: '高可用架構:避免單台伺服器當機導致整體系統掛掉' },
      ],
    },
    {
      id: 'load-balancer',
      title: '在系統設計面試中如何談 Load Balancer',
      blocks: [
        { type: 'paragraph', text: '在系統設計面試時,不要在每個服務前面都畫一個 Load Balancer,這樣顯得多餘, 甚至會讓設計圖變得混亂。比較好的做法有兩種:' },
        { type: 'list', ordered: true, items: ['乾脆省略不畫,只要提到「這些服務是水平擴展的」就可以了。', '只在整個系統入口畫一個 Load Balancer,作為抽象層,表示流量會被分配到多台'] },
        { type: 'paragraph', text: '服務實例。' },
        { type: 'paragraph', text: '另外,有些情境下,你需要特定的 Load Balancer 功能:' },
        { type: 'paragraph', text: 'Sticky Sessions(黏性會話) → 確保同一用戶的請求都導向同一伺服器,例如購 物車' },
        { type: 'paragraph', text: 'Persistent Connections(長連線) → 像 WebSockets,需要連線固定在同一後 端' },
        { type: 'paragraph', text: '在面試中,最常見的判斷是:要用 L4 還是 L7 的 Load Balancer?' },
        { type: 'paragraph', text: 'L4 (Transport Layer) → 基於 TCP/UDP,適合長連線(如 WebSocket),因為 它只管傳輸,不會頻繁斷開重建' },
        { type: 'paragraph', text: 'L7 (Application Layer) → 基於 HTTP/HTTPS,能根據 URL、Header、Method 做更靈活的流量路由,也能減少下游的連線負擔' },
        { type: 'paragraph', text: '速答法則:' },
        { type: 'paragraph', text: '如果有 WebSocket 或持久連線 → 用 L4 LB' },
        { type: 'paragraph', text: '如果是 一般 Web 流量 → 用 L7 LB,因為它提供更靈活的路由' },
      ],
    },
  ],
};
